# jwt
sky:
  jwt:
    # 管理端
    admin-secret-key: rein
    admin-ttl: 7200000
    admin-token-name: token
    # 用户端
    user-secret-key: rein
    user-ttl: 7200000
    user-token-name: authentication

# ??????
server:
  port: 8080

# 下划线和驼峰转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true


spring:
  redis:
    # ?????
    host: 127.0.0.1
    # ???
    port: 6379
    #?????
    database: 0
    # ??????
    connect-timeout: 1800000
    lettuce:
      pool:
        # ????????
        max-active: 20
        # ????????????????
        max-wait: -1
        # ?????????
        max-idle: 5
        # ??????
        min-idle: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sky_take_out?allowMultiQueries=true

  # mvc和swagger冲突
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 阿里云
alioss:
  endpoint: oss-cn-chengdu.aliyuncs.com
  access-key-id: 
  access-key-secret: 
  bucket-name: sky-take-out-rein

# 微信配置
wechat:
  appid: 
  secret: 

